theme: jekyll-theme-minimal
title: Scott Robert Patterson
description: If you are looking for the Scott Robert Patterson that is a PhD student in Political Science at McGill University and NOT an actor from the Gilmore Girls, then you've come to the right place. 
